services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $namespacePrefix: '%elegant_maker.namespace_prefix%'
            $dirPrefix: '%elegant_maker.dir_prefix%'
            $exceptionNamespace: '%elegant_maker.exception.root_namespace%'
            $exceptionDirectory: '%elegant_maker.exception.target_directory%'

    # Register all services in the Generator namespace
    Atournayre\Bundle\MakerBundle\Generator\:
        resource: '../../Generator/*'
        exclude: '../../Generator/{MakerInterface.php}'
        tags: ['elegant.maker']


    # Register commands for all makers
    Atournayre\Bundle\MakerBundle\Command\MakerCommand:
        factory: ['@Atournayre\Bundle\MakerBundle\Command\CommandFactory', 'createCommands']
        tags: ['console.command']

    # Command factory service
    Atournayre\Bundle\MakerBundle\Command\CommandFactory:
        arguments:
            $makers: !tagged_iterator elegant.maker
